

#SWITCH

---

- name: SWITCH
  hosts: switch
  gather_facts: false
  connection: local

  tasks:
    include_tasks: dhcp.yml



#CUCM

- name: CUCM
  hosts: cucm
  gather_facts: false
  connection: local

  tasks:
    include_tasks: cucm.yml


#EDGE

- name: EDGE
  hosts: edge
  gather_facts: false
  connection: local

  tasks:
    include_tasks: edge.yml
